### ISSUE TITLE
Category page

### ISSUE THREAD

**Issue by thomas-thaulow** [meanbee/magento-estimateddelivery#5]
Would it be possible to show the estimate on a product page somehow? Lets say showing estimated delivery date for a specific shipping option?

**Comment by bobbyshaw** [comment]
There's a helper available that you could use to do this, passing in the default shipping method that you want. This is actually a similar approach to what we do at the checkout, except we're looping through all available methods: https://github.com/meanbee/magento-estimateddelivery/blob/master/app/design/frontend/base/default/template/meanbee/estimated_delivery/checkout/onepage/shipping_method/available.phtml#L47
